apiVersion: 1

datasources:
  - name: sensor_db
    type: mysql
    url: 127.0.0.1:3306
    database: sensor_db
    user: sensor_user
    secureJsonData:
      password: "Sensor@Pass1"
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      timeInterval: "1s"
    isDefault: true
    editable: false
